# Generated by Django 3.2.4 on 2021-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_libros', '0002_auto_20210629_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='libro',
            name='autor_id',
            field=models.ManyToManyField(to='app_libros.Autor'),
        ),
    ]
