# Generated by Django 3.2.4 on 2021-07-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_libros', '0004_auto_20210704_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['id'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor_id',
            field=models.ManyToManyField(related_name='autor', to='app_libros.Autor'),
        ),
    ]
